version: '3.8'

services:
  kafka:
    image: 'confluentinc/cp-kafka:7.6.1'
    ports:
      - '9092:9092'
    environment:
      # KRaft settings for ZooKeeper-less Kafka
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://kafka:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - 'kafka_data:/var/lib/kafka/data'

  kafka-ui:
    image: 'docker.redpanda.com/redpandadata/console:v2.4.5'
    ports:
      - '${KAFKA_UI_HOST_PORT:-8081}:8080'
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKERS=kafka:9092

  redis:
    image: 'redis:7.2'
    ports:
      - '6379:6379' # Standard Redis port, often left as is
    volumes:
      - 'redis_data:/data'

  postgres:
    image: 'postgres:13'
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - 'postgres_db_data:/var/lib/postgresql/data'
      - ./postgres:/docker-entrypoint-initdb.d

  airflow-init:
    build:
      context: .
      dockerfile: ./airflow/Dockerfile
    entrypoint: /bin/bash -c "airflow db init && airflow users create --username admin --password admin --firstname admin --lastname admin --role Admin --email admin@example.com"
    depends_on:
      - postgres

  airflow-webserver:
    build:
      context: .
      dockerfile: ./airflow/Dockerfile
    ports:
      - '${AIRFLOW_HOST_PORT:-8080}:8080'
    depends_on:
      - postgres
      - airflow-init
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False

  airflow-scheduler:
    build:
      context: .
      dockerfile: ./airflow/Dockerfile
    depends_on:
      - postgres
      - airflow-init
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False

  mlflow-db-upgrade:
    build:
      context: .
      dockerfile: ./mlflow_custom/Dockerfile
      args:
        MLFLOW_IMAGE_TAG: ${MLFLOW_IMAGE_TAG:-v2.17.0}
    command: >
      mlflow db upgrade postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
    depends_on:
      - postgres

  mlflow:
    build:
      context: .
      dockerfile: ./mlflow_custom/Dockerfile
      args:
        MLFLOW_IMAGE_TAG: ${MLFLOW_IMAGE_TAG:-v2.17.0}
    ports:
      - '${MLFLOW_HOST_PORT:-5001}:5000'
    command: >
      mlflow server
      --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${MLFLOW_DB}
      --default-artifact-root mlflow-artifacts:/
      --artifacts-destination /mlruns
      --host 0.0.0.0
    depends_on:
      - mlflow-db-upgrade
    volumes:
      - ./mlflow_custom/mlruns:/mlruns

  gatekeeper:
    build:
      context: .
      dockerfile: ./services/gatekeeper/Dockerfile
    ports:
      - '${GATEKEEPER_HOST_PORT:-8000}:8000'
    depends_on:
      - kafka
      - redis
    volumes:
      - ./services/gatekeeper/src:/app/src
      - ./recommender_schemas:/app/recommender_schemas
    environment:
      - PYTHONPATH=/app

  data_producer:
    build:
      context: .
      dockerfile: ./services/data_producer/Dockerfile
    depends_on:
      - kafka
    volumes:
      - ./services/data_producer/src:/app/src
      - ./recommender_schemas:/app/recommender_schemas
      - ./data:/app/data 
    environment:
      - PYTHONPATH=/app

  trainer:
    build:
      context: .
      dockerfile: ./services/trainer/Dockerfile
    depends_on:
      - kafka
      - mlflow
    volumes:
      - ./services/trainer/src:/app/src
      - ./services/trainer/dags:/app/dags
      - ./recommender_schemas:/app/recommender_schemas
      - ./data:/app/retailrocket/data
    environment:
      - PYTHONPATH=/app

volumes:
  kafka_data:
  redis_data:
  postgres_db_data:
  mlflow_data:
